### ISSUE TITLE
TransformationServiceImplTest failing sometimes

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#130]
Sometimes a build fails due to this issue (Log has been taken from jenkins)

 ```
Fehler
expected:<DONE> but was:<READY>
Stacktrace
java.lang.AssertionError: expected:<DONE> but was:<READY>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.opentosca.toscana.core.transformation.TransformationServiceImplTest.startTransformationInternal(TransformationServiceImplTest.java:167)
	at org.opentosca.toscana.core.transformation.TransformationServiceImplTest.startTransformation(TransformationServiceImplTest.java:104)
Standard Output
16:53:26.473 [main] INFO  o.o.toscana.core.util.Preferences    datadir is 'testsuite-spring-tmpdir/'
16:53:26.473 [main] INFO  o.o.toscana.core.util.Preferences    Data directory is /var/lib/jenkins/workspace/TOSCAna_master-LC5KDTWNQ7ME2HKUYP5XIGTBFGBOVL6D2PY6GZIFGKC4APVBG7RA/core/testsuite-spring-tmpdir
16:53:26.479 [main] INFO  o.o.t.core.plugin.PluginServiceImpl  Loaded 8 Plugins
16:53:26.484 [main] INFO  o.o.t.c.t.a.ArtifactServiceImpl      Artifact directory is /var/lib/jenkins/workspace/TOSCAna_master-LC5KDTWNQ7ME2HKUYP5XIGTBFGBOVL6D2PY6GZIFGKC4APVBG7RA/core/testsuite-spring-tmpdir/artifacts
16:53:26.497 [main] DEBUG CsarFilesystemDao                    in-memory csars in synced with file system
16:53:26.577 [main] INFO  o.o.toscana.core.BaseSpringTest      cleaned up disk
16:53:26.582 [main] DEBUG o.o.toscana.core.util.ZipUtility     Creating directory: testsuite-spring-tmpdir/simple-taskcsar/content/docker/
16:53:26.584 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerengine_start.sh
16:53:26.584 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerengine_create.sh
16:53:26.585 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_create.sh
16:53:26.585 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_start.sh
16:53:26.586 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_stop.sh
16:53:26.586 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerengine_stop.sh
16:53:26.586 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_delete.sh
16:53:26.586 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockertypes.yaml
16:53:26.587 [main] DEBUG o.o.toscana.core.util.ZipUtility     Creating directory: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/
16:53:26.591 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/index.php
16:53:26.593 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/Dockerfile
16:53:26.597 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/createdb.sql
16:53:26.599 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/mysql-credentials.php
16:53:26.601 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/template.yaml
16:53:26.602 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/zip
16:53:26.602 [main] INFO  CsarFilesystemDao                    extracted csar 'simple-taskcsar' into 'testsuite-spring-tmpdir/simple-taskcsar/content'
16:53:26.653 [main] DEBUG o.o.toscana.core.util.ZipUtility     Creating directory: testsuite-spring-tmpdir/simple-taskcsar/content/docker/
16:53:26.653 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerengine_start.sh
16:53:26.654 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerengine_create.sh
16:53:26.658 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_create.sh
16:53:26.658 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_start.sh
16:53:26.659 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_stop.sh
16:53:26.659 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerengine_stop.sh
16:53:26.659 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockerapp_delete.sh
16:53:26.681 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/docker/dockertypes.yaml
16:53:26.682 [main] DEBUG o.o.toscana.core.util.ZipUtility     Creating directory: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/
16:53:26.685 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/index.php
16:53:26.685 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/Dockerfile
16:53:26.686 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/createdb.sql
16:53:26.688 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/simple-task-app/mysql-credentials.php
16:53:26.693 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/template.yaml
16:53:26.694 [main] DEBUG o.o.toscana.core.util.ZipUtility     Extracting file: testsuite-spring-tmpdir/simple-taskcsar/content/zip
16:53:26.697 [main] INFO  CsarFilesystemDao                    extracted csar 'simple-taskcsar' into 'testsuite-spring-tmpdir/simple-taskcsar/content'
16:53:26.698 [main] INFO  o.o.t.c.t.TransformationFilesystemDao deleted transformation directory 'testsuite-spring-tmpdir/simple-taskcsar/transformations/testplatform_passing_dummy'
16:53:26.765 [pool-9-thread-1] INFO  o.o.t.c.t.execution.ExecutionTask    Starting Transformation executor for simple-taskcsar/testplatform_passing_dummy
16:53:26.791 [main] INFO  o.o.toscana.core.BaseSpringTest      cleaned up disk
16:53:26.810 [pool-9-thread-1] INFO  o.o.t.c.dummy.ExecutionDummyPlugin   Waiting 50ms until completion
```

**Comment by c-mueller** [comment]
I think this issue is fixed, did not encounte that problem again after increasing the delays. to 100 ms instead of 10 ms
