### ISSUE TITLE
CloudFoundry support for nodetype 'Database'

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#446]
While testing I've tried to perform a transformation of a template containing a node of type 'Database' (not MysqlDatabase). 

###  test data
```yaml
tosca_definitions_version: tosca_simple_yaml_1_1

description: template for testing database node
metadata:
  template_name: database
  template_author: stupro-toscana
  template_version: 1.0

topology_template:
  node_templates:
    test_node:
      type: Database
      properties:
        port: 8084
```

### Expected behaviour
Database nodes are handled like MysqlDatabase nodes.

### Wittnessed behaviour
```
org.opentosca.toscana.model.visitor.UnsupportedTypeException: Type 'org.opentosca.toscana.model.node.Database' is not supported
	at org.opentosca.toscana.model.visitor.StrictNodeVisitor.visit(StrictNodeVisitor.java:53)
	at org.opentosca.toscana.model.node.Database.accept(Database.java:156)
	at org.opentosca.toscana.plugins.cloudfoundry.CloudFoundryLifecycle.transform(CloudFoundryLifecycle.java:93)
	at org.opentosca.toscana.core.plugin.lifecycle.ExecutionPhase.execute(ExecutionPhase.java:49)
	at org.opentosca.toscana.core.plugin.TOSCAnaPlugin.transform(TOSCAnaPlugin.java:112)
	at org.opentosca.toscana.core.transformation.execution.ExecutionTask.transform(ExecutionTask.java:78)
	at org.opentosca.toscana.core.transformation.execution.ExecutionTask.run(ExecutionTask.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mklopp** [comment]
Actually this is not completely right. The expected behavior isn't that these are handled but that the checkModel verification should return false if there is a database node in the model because we currently not yet supporting these.

**Comment by hnicke** [comment]
But think about it: Why should we reject a template which contains a 'Database' node? The plugin does support a specialization of the node..

**Comment by JensMueller2709** [comment]
We support a specialization of the Database node, right. But that is not meaning that we have to support the general Database node. This is more complex than the SQL Database Node.
