### ISSUE TITLE
Ensure Transformation logging is Thread save

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#65]
This problem is not very important, thats why i assigned it low priority.

We currently have a small problem with the transformation logging implementation.
Lets say we have two threads with a logger for each one (bound to the same Log Object). The first thread is appending the stack trace of a exception and the other one is just writing some message. The current implementation could result in a logging output that looks like this (Taken from the unit test for the logging appender, Line 20 and 21):

```
20:03:31.740 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 1: Something went wrong
20:03:31.740 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 2: java.lang.RuntimeException: Test exception
20:03:31.740 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 3: at org.opentosca.toscana.core.transformation.logging.TransformationAppenderTest.testAppenderStackTrace(TransformationAppenderTest.java:55)
20:03:31.740 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 4: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:03:31.740 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 5: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:03:31.740 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 6: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:03:31.740 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 7: at java.lang.reflect.Method.invoke(Method.java:498)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 8: at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 9: at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 10: at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 11: at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 12: at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 13: at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 14: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 15: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 16: at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 17: at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 18: at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 19: at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 20: Initialisation done sucessfully
20:03:31.741 [main] INFO  o.o.t.c.t.l.TransformationAppenderTest Line 21: at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
``` 

But the message at Line 20 should either be shown before or after the stack trace.

**Comment by c-mueller** [comment]
I Consider this irrelevant, because a transfomation is a single threaded task.
